### ISSUE TITLE
Moodboard

### ISSUE THREAD

**Issue by MitsuMimi** [wizardamigosinstitute/wizardamigosinstitute.github.io#41]
## `@todo`
- [x] Idea : Find inspiration for neat, clean design: [results `2022.02.25`][1]
- [x] Find website that _look_ like a game: [results `2022.02.25`][1]
- [x]  The logo is a Pixel Art typeOf logo, let's make a website Pixel Art themed, perhaps a game like : Make a mood board for pixel art websites : [Results `2022.03.05`](https://github.com/wizardamigos/wizardamigos.github.io/issues/41#issuecomment-1059938818)
* [ ] The choice how to go exactly about the website or “game” depends on the slide deck with a good concept, which we need to finish first
* [ ] start checking inspirational pages and get feedback to refine concept
* [ ] collect design ideas to iterate on concept
* [ ] the “moodboards” you made in figma should be added to a public pinterest moodboard so we can link it as a result
the links and other inspirational resources and work results should be attached as links to the corresponding github issue or alternatively should be in a markdown document on github itself (you would need to create a pull request) and then you link that document in the github issues
  * [ ] start checking inspirational pages and get feedback to refine concept
  * [ ] collect design ideas to iterate on concept

---
**Ninas Video** https://watch.screencastify.com/v/p3kdx02CVCyM8qdy6myB

[1]: https://github.com/wizardamigos/wizardamigos.github.io/issues/41#issuecomment-1055861428

**Comment by mimi-uxui-dev** [comment]
WorkLog Video 24-25/02/2022 : https://www.youtube.com/watch?v=yr49xtmqKpI&feature=youtu.be&ab_channel=Mimi   

WorkLog Summary :

**Comment by mimi-uxui-dev** [comment]
Desicions & Results :
- Organize the moodboard: made 5 frames (General moodboard, fonts, colors, icons and logos)
(1) https://www.figma.com/file/lk41O0wlkMEdPiCBGVMOO8/Wizard-Amigos?node-id=0%3A1

**Comment by mimi-uxui-dev** [comment]
Decisions & Results :
- Organize the moodboard: made 5 frames (General moodboard, fonts, colors, icons and logos)
- (1) https://www.figma.com/file/lk41O0wlkMEdPiCBGVMOO8/Wizard-Amigos?node-id=0%3A1
- (2) links:
  - https://www.hellfest.fr/
  - https://madbox.io/
  - https://www.vroomgame.com/#thegame
  - https://www.pinterest.de/serapath/wizardamigos/
  - https://phaser.io/learn
  - http://rastating.github.io/pixel.js/documentation/
  - https://github.com/tylerreichle/mario_js
  - https://2021.fanzone36.com/en/home
  - Tutorial Super Mario game made with javascript :  https://www.youtube.com/watch?v=g-FpDQ8Eqw8&ab_channel=MethMethMethod

**Comment by serapath** [comment]
[**feedback `2022.03.01`**](https://hackmd.io/wb60JdOrQZCI-1B6hfdBIg)

**Comment by mimi-uxui-dev** [comment]
[**Worklog `2022.03.05` Part 1**](https://youtu.be/KnhiLNUJGtY)
[**Worklog `2022.03.05` Part 2**](https://youtu.be/KnhiLNUJGtY)
**Results `2022.03.05`** : [HackMD File](https://hackmd.io/@mimiuxui/S16BcGW-q) + [Pintrest MoodBoard](https://www.pinterest.com/uxuimimi/wizard-amigos-pixel-art-theme/)

**Comment by serapath** [comment]
**feedback `2022.03.06`**

the moodboard hackmd and pinterest are lovely. interesting to see that it includes a pixelart editor too, that's cool. a lot of inspiration, but watching all of it i still can't say what a good next move would be regarding the overall bigger picture.

maybe it would be easier to flesh out designs and mechanics for individual pieces, like:
1. how is a workshop made?
2. how do you see all the workshops you made?
3. how does it look like when a user goes through a workship?
4. how does a user see the workshops they already solved?
5. how does a user look at other peoples workshops?

Keep in mind:
1. all workshops are a json file which is then turned into a themed somewhat standardized workshop view app any user can use to learn the workshop
2. every workshop is published under a unique domain with a unique theme
3. every person has their profile published under a unique domain, like people publish their own blogs and they have their own theme
4. every such unique website with its own domain can fetch some json data from other pages

**maybe if we work on this and have some sketches and designs, probably even wireframes of how each of them works, the other things are easier to answer?**

oh also:
1. somebody can handpick and make a finite set of workshops into a code camp (like a "playlist of workshops") and publish it under its own unique domain. how does that look?

*We should assume the people who make workshops or codecamps or profiles dont know anything about design or web development other then maybe how to upload something to their own webspace and register a domain for it so it shows*

how can we make the above as cool as possible? :-)

**Comment by mimi-uxui-dev** [comment]
[**Worklog `2022.03.07`**](https://youtu.be/0KUk8WjD-_8) : Stared Wireframing
**Results `2022.03.07`** [Wizard Amigos Draft 01](https://www.figma.com/file/lk41O0wlkMEdPiCBGVMOO8/Wizard-Amigos?node-id=57%3A2)
