### ISSUE TITLE
profile page concept & design

### ISSUE THREAD

**Issue by MitsuMimi** [wizardamigosinstitute/wizardamigosinstitute.github.io#51]
## `@todo`
* [ ] make profile page concept & design
  * `@input` :package: [`what have we built hackmd`](https://hackmd.io/@mimiuxui/ryTf3nkW5) from #45
  * `@input` :package: [`history content slides`](https://slides.com/taouskhoudour/palette/fullscreen#/1) from #45  
  - `@input` :package: [`brief summary slide deck`](https://slides.com/taouskhoudour/wizard-amigos) from #42
  * `@input` :package: [`concept outline description`](https://hackmd.io/@mimiuxui/rkpwZmO1q) from #46
  - [ ] brainstorm UI/UX
    - [ ] submitting a feedback is opening or participating with info or bounty in an existing feedback gig, so it will anyway show on the users profile and the user can (auto)subscribe to it
    - [ ] users can see their currently ongoing gigs so they can quickly jump back to the workshop into the view of your gig
    * [ ] display available actions
    * [ ] Display history: history contains everything a user went through which includes workshops, gigs, exercises, code camps .. etc
    * [ ] Display notification history 
    * [ ] #72
    * [ ] Initially **notes** which are a HackMD file can be **`linked`** via config to be made available to specific apps (e.g. like workshops)
    * [ ] list of created workshops
    * [ ] list of contributed / attended to workshops
    * [ ] list of achievements 
    * [ ] Workshop Statistics
    * [ ] Gigs Statistics
    * [ ] Code Camps Statistics
    * [ ] Notes Statistics
    * [ ] ??? profile dashboard viewer concept & design
      - [ ] brainstorm UI/UX
      - [ ] create outputs
      - `@output`: :question: `profile dashboard slides`
      - `@output`: :question: `profile dashboard linked markdown file per slide in "./slides/<slidename>.md"`
      - `@output`: :question: `profile dashboard wireframes`
  - [ ] create slides, wireframes and markdown files
  * `@output` :question: `profile page viewer slides`
    * next #61
  * `@output` :question: `profile page viewer wireframes`
    * next #61
  * `@output` :question: `profile page viewer linked markdown file per slide in "./slides/<slidename>.md"`
    * next #61
  * `@output` :question: `profile page data generator slides`
    * next #61
  * `@output` :question: `profile page data generator wireframes`
    * next #61
  * `@output` :question: `profile page data generator linked markdown file per slide in "./slides/<slidename>.md"`
    * next #61
  * `@output` :question: `profile page data editor slides`
    * next #61
  * `@output` :question: `profile page data editor wireframes`
    * next #61
  * `@output` :question: `profile page data editor linked markdown file per slide in "./slides/<slidename>.md"`
    * next #61

---

## `@info`
...

**Comment by serapath** [comment]
**feedback `2022.03.17`**
the profile page packs a lot.

given my previous feedback, which i will try to copy/move to another comment on this issue, the profile will be something "generic" not really related to wizardamigos similar to how a crypto wallet like metamask does not belong to a specific "dapp" (decentralized app) a user interacts with.

so, next to tools like:
* create gig
* open and watch skill tree
* edit profile info (e.g. email)
* show my solved code camps
* show my solved workshops
* list my authored workshops
  * accept/reject a maintainer/contributor to it
* list my authored codecamps
  * accept/reject a maintainer/contributor to it

...there will be many more things, because as said before, the profile page is generic, so we need to find a standardized way how any other app a user wants to use using their (wizardamigos) profile (think: "sign in with facebook") ...but sign in with wizardamigos...

**how can an app "add" a section about itself to the users "profile page"?**

**how can a user manage permissions of an app on their profile page? (think: manage app permissions on facebook)**
