### ISSUE TITLE
skilltree viewer concept & design

### ISSUE THREAD

**Issue by MitsuMimi** [wizardamigosinstitute/wizardamigosinstitute.github.io#52]
## `@todo`
* [ ] make skilltree viewer concept & design
  * `@input` :package: [`what have we built hackmd`](https://hackmd.io/@mimiuxui/ryTf3nkW5) from #45
  * `@input` :package: [`history content slides`](https://slides.com/taouskhoudour/palette/fullscreen#/1) from #45  
  - `@input` :package: [`brief summary slide deck`](https://slides.com/taouskhoudour/wizard-amigos) from #42
  * `@input` :package: [`concept outline description`](https://hackmd.io/@mimiuxui/rkpwZmO1q) from #46
  - [ ] brainstorm UI/UX
    * [ ] revisit feedback in comments below
    * `@result` :package: [`inspirational links`](https://hackmd.io/@mimiuxui/SkKkwDYg9) from [comment](https://github.com/wizardamigos/wizardamigos.github.io/issues/52#issuecomment-1086771542)
    * [ ] on the skill tree page all paths and workshops and code camps a user did already or gigs they did could be displayed on the skill tree map as colors or other icon indicators
    * [ ] a button to toggle the view to show what is done and what not
    * [ ] mini map
  - [ ] create slides, wireframes and markdown files
  * `@output` :question: `skilltree viewer slides`
    * next #63
  * `@output` :question: `skilltree viewer wireframes`
    * next #63
  * `@output` :question: `skilltree viewer linked markdown file per slide in "./slides/<slidename>.md"`
    * next #63

---

## `@info`
...

**Comment by serapath** [comment]
> @mimi-uxui-dev 
> https://hackmd.io/@mimiuxui/SkKkwDYg9

**Comment by serapath** [comment]
[**feedback `2022.03.01`:** concept & game idea](https://hackmd.io/wb60JdOrQZCI-1B6hfdBIg)

**Comment by serapath** [comment]
> @mimi-uxui-dev 
> [Worklog Video `2022.03.02`](https://youtu.be/g06VYu6qYzA) : Commentary on  [Feedback `2022.03.01` : concept & game idea](https://github.com/wizardamigos/wizardamigos.github.io/issues/52#issuecomment-1086771583)
