### ISSUE TITLE
themes design

### ISSUE THREAD

**Issue by MitsuMimi** [wizardamigosinstitute/wizardamigosinstitute.github.io#58]
## `@todo`
* [ ] make video-player concept & design
  * `@input` :package: [`what have we built hackmd`](https://hackmd.io/@mimiuxui/ryTf3nkW5) from #45
  * `@input` :package: [`history content slides`](https://slides.com/taouskhoudour/palette/fullscreen#/1) from #45  
  - `@input` :package: [`brief summary slide deck`](https://slides.com/taouskhoudour/wizard-amigos) from #42
  * `@input` :package: [`concept outline description`](https://hackmd.io/@mimiuxui/rkpwZmO1q) from #46
  * `@input` :question: `wizardamigos theme & design` from #39
  * `@input` :question: `refined concept slide deck` from #73
  - [ ] brainstorm UI/UX
    * [ ] User Research Survey
    * [ ] User persona
    * [ ] Empathy map
    * [ ] decide for logos, colors, fonts, images, icon sets, etc... 
    * [ ] #41 
  * [ ] decide for logos, colors, fonts, images, icon sets, etc... 
  * [ ] design multiple wizardamigos UI/UX themes (dark, light, etc...)
    * [ ] make sure to include a dark mode and light mode theme
  * `@output` :question: `multiple wizardamigos coded themes (config/css/images/icons/assets)`
    * next #74
    - next #79
    - next #82

---

## `@info`
...
