### ISSUE TITLE
make theme tool components

### ISSUE THREAD

**Issue by MitsuMimi** [wizardamigosinstitute/wizardamigosinstitute.github.io#71]
## `@todo`
* [ ] make theme tool components
  * `@input` :question: `refined concept slide deck` from #73
  * `@input`: :question: `theme editor slides` from #37
  * `@input`: :question: `theme editor linked markdown file per slide in "./slides/<slidename>.md"` from #37
  * `@input`: :question: `theme editor wireframes` from #37
  * `@input`: :question: `theme picker slides` from #37
  * `@input`: :question: `theme picker linked markdown file per slide in "./slides/<slidename>.md"` from #37
  * `@input`: :question: `theme picker wireframes` from #37
  - [ ] implement
      * [ ] theme editor
      * [ ] picker (allow switching between dark/light/etc... mode)
      * [ ] re-use or implement sub components
  - [ ] implement theme tool components
    * `@output` :question: `theme editor component`
      * next #74
    * `@output` :question: `theme picker component`
      * next #74

---

## `@info`
...
