### ISSUE TITLE
present finished project

### ISSUE THREAD

**Issue by serapath** [wizardamigosinstitute/wizardamigosinstitute.github.io#82]
## `@todo`
* [ ] prepare presentation of all final project results
  * `@input` :question: `refined concept slide deck` from #73
  * `@input` :question: `wizardamigos website` from #80
  * `@input` :question: `wizardamigos codecamp` from #83
  * `@input` :question: `multiple wizardamigos coded themes (config/css/images/icons/assets)` from #58
  * `@input` :question: `design system website` from #74
  * `@input` :question: `workshop-workshop page with one exercise` from #81
  * `@input` :question: `codecamp-workshop page with one exercise` from #81
  * `@input` :question: `gig/exercise-workshop page with one exercise` from #81
  * `@input` :question: `updated playproject-io website` from #79
* [ ] record screencast video to present prepared presentation
   * `@result` :question: `youtube video with recorded project presentation`
     * next #38
* [ ] schedule and do video call to present to @ninabreznik and discuss results afterwards to take feedback notes 
   * `@input` :question: `youtube video with recorded project presentation`
  * `@result` :question: `feedback notes`
* [ ] refine results based on feedback
  * `@input` :question: `feedback notes`
  * `@input` :question: `refined concept slide deck` from #73
  * `@input` :question: `wizardamigos website` from #80
  * `@input` :question: `wizardamigos codecamp` from #83
  * `@input` :question: `multiple wizardamigos coded themes (config/css/images/icons/assets)` from #58
  * `@input` :question: `design system website` from #74
  * `@input` :question: `workshop-workshop page with one exercise` from #81
  * `@input` :question: `codecamp-workshop page with one exercise` from #81
  * `@input` :question: `gig/exercise-workshop page with one exercise` from #81
  * `@input` :question: `updated playproject-io website` from #79
  * [ ] record screencast of refined concept slide deck to present project
  * `@output` :question: :checkered_flag: `refined recorded presentation`
  * `@output` :question: :checkered_flag: `refined - design system page to showcase all components themed`
  * `@output` :question: :checkered_flag: `refined - multiple themes`
  * `@output` :question: :checkered_flag: `refined - wizardamigos website`
  * `@output` :question: :checkered_flag: `refined - workshop-workshop page`
  * `@output` :question: :checkered_flag: `refined - codecamp-workshop page`
  * `@output` :question: :checkered_flag: `refined - gig/exercise-workshop page`
  * `@output` :question: :checkered_flag: `refined - wizardamigos codecamp`
  * `@output` :question: :checkered_flag: `refined - updated playproject-io website`

---

## `@info`
...
